#!/usr/bin/env bats
# CUJ-03 — a stranger who wants to reuse a piece of this learns what they may do.

@test "LICENSE is Apache-2.0 with the copyright line completed" {
  [ -f LICENSE ]
  grep -q 'Apache License' LICENSE
  grep -q 'Version 2.0' LICENSE
  # The appendix ships with [yyyy] and [name of copyright owner] as placeholders.
  # Leaving them is the common failure: the file looks like a licence and grants
  # nothing identifiable.
  ! grep -q '\[yyyy\]' LICENSE
  ! grep -q 'name of copyright owner' LICENSE
  grep -qE '^\s*Copyright [0-9]{4} .+' LICENSE
}

@test "the README states the terms" {
  grep -qiE '^#+ License' README.md
  # Naming the licence is not enough; a reader has to be able to reach the text.
  run bash -c "sed -n '/^#\+ License/,/^#\+ /p' README.md"
  [ "$status" -eq 0 ]
  echo "$output" | grep -qi 'Apache'
  echo "$output" | grep -q 'LICENSE'
}

@test "content that is not ours is identified with its own licence" {
  # The beads hooks and the marked blocks in AGENTS.md/CLAUDE.md are generated by
  # bd, which is MIT. A blanket Apache-2.0 header over the repo would purport to
  # relicense them, so the origin has to be recorded somewhere tracked.
  [ -f NOTICE ]
  grep -qi 'beads' NOTICE
  grep -q 'MIT' NOTICE
  # And the claim must be true of the tree: if the generated files go away, the
  # NOTICE entry is stale and should fail rather than linger.
  [ -f .beads/hooks/pre-commit ]
  grep -q 'BEGIN BEADS INTEGRATION' .beads/hooks/pre-commit
}
