#!/usr/bin/env bash
# Derive llama-swap's macro overlay from .env.
#
# llama-swap does not read KEY=value: it treats ${...} as its own macro
# namespace and fails to load on any undeclared name. So the human edits .env
# and this writes the machine half of the serving config from it.
#
# A macro may be defined exactly once across every file llama-swap loads --
# two sources setting one differently is a fatal conflict in either ordering.
# That is why the tracked configs define no path macros at all, and why this
# file defines nothing the tracked configs already do.
set -euo pipefail

REPO_DEFAULT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENVFILE="${1:-$REPO_DEFAULT/.env}"
OUTDIR="${2:-$HOME/.config/llama-swap}"

[ -f "$ENVFILE" ] || { echo "[FAIL] no $ENVFILE. Run scripts/env-init.sh first." >&2; exit 1; }

set -a; . "$ENVFILE"; set +a
: "${MODELS:?MODELS is not set in $ENVFILE}"
: "${OPT:?OPT is not set in $ENVFILE}"
REPO="${REPO:-$REPO_DEFAULT}"

for d in "$MODELS" "$OPT" "$REPO"; do
  case "$d" in
    /*) ;;
    *) echo "[FAIL] paths in $ENVFILE must be absolute, got: $d" >&2; exit 1 ;;
  esac
done

mkdir -p "$OUTDIR"
cat > "$OUTDIR/00-paths.yaml" <<EOF
# GENERATED by scripts/env-overlay.sh from $ENVFILE -- edit that, not this.
#
# Supplies the machine half of the serving contract. The tracked configs in
# config/ reference these and define none of them, so neither file works alone
# and neither carries anyone's home directory.
macros:
  m: $MODELS
  opt: $OPT
  repo: $REPO
EOF
echo "  [+] wrote $OUTDIR/00-paths.yaml (m=$MODELS opt=$OPT)"
